site_name: Happy Hub
site_url: https://happyhub.in
repo_url: https://github.com/puneetkkala/puneetkkala.github.io
repo_name: puneetkkala/puneetkkala.github.io

nav:
  - Home: index.md
  - About: about.md
  - Blog:
    - Introduction: blog/index.md
    - Medical Model: blog/medical-model.md
  - Legal:
    - Disclaimer: legal/disclaimer.md
    - Privacy Policy: legal/privacy.md
    - License: legal/license.md
    - Sources and Credits: legal/sources.md
  - Contact: contact.md

theme:
  name: material
  theme:
  palette: 
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  language: en
  logo: assets/logo.png
  favicon: assets/logo.png
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    - toc.follow
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - header.autohide
    - navigation.footer
    - content.code.copy
  icon:
    repo: fontawesome/brands/github
extra_css:
  - stylesheets/extra.css
extra:
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our website and whether users
      find what they're searching for. With your consent, you're helping us to
      make our website better.
  social:
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@happy-hub-yt
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/puneetkkala
    - icon: fontawesome/brands/github
      link: https://github.com/puneetkkala
    - icon: fontawesome/brands/medium
      link: https://medium.com/@puneetkkala
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/kalapuneet/
    - icon: fontawesome/solid/envelope
      link: mailto:puneet@happyhub.in
  analytics:
    provider: google
    property: !ENV GA_ID
    feedback: 
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >- 
            Thanks for your feedback!
copyright: >
  Copyright &copy; 2024-2025 Puneet Kala -
  <a href="#__consent">Change cookie settings</a>
plugins:
  - search
  - social
  - tags
  - offline
  - git-revision-date-localized:
      enable_creation_date: true
markdown_extensions:
  - abbr
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - tables